const quijoteFrases = [
  "En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga antigua, rocín flaco y galgo corredor.",
  "Una olla de algo más vaca que carnero, salpicón las más noches, duelos y quebrantos los sábados, lentejas los viernes, algún palomino de añadidura los domingos, consumían las tres partes de su hacienda.",
  "El resto della concluían sayo de velarte, calzas de velludo para las fiestas con sus pantuflos de lo mesmo, los días de entre semana se honraba con su vellorí de lo más fino.",
  "Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que así ensillaba el rocín como tomaba la podadera.",
  "Frisaba la edad de nuestro hidalgo con los cincuenta años; era de complexión recia, seco de carnes, enjuto de rostro, gran madrugador y amigo de la caza.",
  "Quieren decir que tenía el sobrenombre de Quijada, o Quesada, que en esto hay alguna diferencia en los autores que deste caso escriben; aunque, por conjeturas verosímiles, se deja entender que se llamaba Quijana.",
  "Pero esto importa poco a nuestro cuento; basta que en la narración dél no se salga un punto de la verdad.",
  "Es, pues, de saber que este sobredicho hidalgo, los ratos que estaba ocioso, que eran los más del año, se daba a leer libros de caballerías, con tanta afición y gusto, que olvidó casi de todo punto el ejercicio de la caza, y aun la administración de su hacienda.",
  "Y llegó a tanto su curiosidad y desatino en esto, que vendió muchas hanegas de tierra de sembradura, para comprar libros de caballerías en que leer; y así llevó a su casa todos cuantos pudo haber dellos.",
  "Y de todos ningunos le parecían tan bien como los que compuso el famoso Feliciano de Silva, porque la claridad de su prosa y aquellas intrincadas razones suyas le parecían de perlas.",
  "Especialmente cuando llegaba a leer aquellos requiebros y cartas de desafíos, donde en muchas partes hallaba escrito: la razón de la sinrazón que a mi razón se hace, de tal manera mi razón enflaquece, que con razón me quejo de la vuestra fermosura.",
  "Con estas razones perdía el pobre caballero el juicio, y desvelábase por entenderlas y desentrañarles el sentido, que no se lo sacara ni las entendiera el mismo Aristóteles, si resucitara para sólo ello.",
  "No estaba muy bien con las heridas que don Belianís daba y recibía, porque se imaginaba que, por grandes maestros que le hubiesen curado, no dejaría de tener el rostro y todo el cuerpo lleno de cicatrices y señales.",
  "Pero con todo alababa en su autor aquel acabar su libro con la promesa de aquella inacabable aventura; y muchas veces le vino deseo de tomar la pluma y darle fin al pie de la letra, como allí se promete.",
  "Y sin duda alguna lo hiciera, y aun saliera con ello, si otros mayores y continuos pensamientos no se lo estorbaran.",
  "Tuvo muchas veces competencia con el cura de su lugar (que era hombre docto, graduado en Sigüenza), sobre cuál había sido mejor caballero: Palmerín de Inglaterra o Amadís de Gaula.",
  "Mas maese Nicolás, barbero del mismo pueblo, decía que ninguno llegaba al caballero del Febo, y que si alguno se le podía comparar, era don Galaor, hermano de Amadís de Gaula, porque tenía muy acomodada condición para todo.",
  "En resolución, él se enfrascó tanto en su lectura, que se le pasaban las noches leyendo de claro en claro, y los días de turbio en turbio, y así, del poco dormir y del mucho leer, se le secó el cerebro, de manera que vino a perder el juicio.",
  "Llenósele la fantasía de todo aquello que leía en los libros, así de encantamientos como de pendencias, batallas, desafíos, heridas, requiebros, amores, tormentas y disparates imposibles.",
  "Y asentósele de tal modo en la imaginación que era verdad toda aquella máquina de aquellas sonadas soñadas invenciones que leía, que para él no había otra historia más cierta en el mundo.",
  "Decía él que el Cid Ruy Díaz había sido muy buen caballero; pero que no tenía que ver con el caballero de la Ardiente Espada, que de sólo un revés había partido por medio dos fieros y descomunales gigantes.",
  "Mejor estaba con Bernardo del Carpio, porque en Roncesvalles había muerto a Roldán el encantado, valiéndose de la industria de Hércules, cuando ahogó a Anteo, el hijo de la Tierra, entre los brazos.",
  "Decía mucho bien del gigante Morgante, porque, con ser de aquella generación gigantea, que todos son soberbios y descomedidos, él solo era afable y bien criado.",
  "Pero sobre todos estaba bien con Reinaldos de Montalbán, especialmente cuando le veía salir de su castillo y robar cuantos topaba, y cuando en allende robó aquel ídolo de Mahoma que era todo de oro, según dice su historia.",
  "Diera él, por tener la mano a Reinaldos, al gigante Fierabrás de quien tanto se cuenta, a Bernardo del Carpio, y a todos los demás que andaban por el mundo.",
  "Finalmente, rematado ya su juicio, vino a dar en el más extraño pensamiento que jamás dio loco en el mundo, y fue que le pareció convenible y necesario, así para el aumento de su honra como para el servicio de su república, hacerse caballero andante.",
  "E irse por todo el mundo con sus armas y caballo a buscar las aventuras, y a ejercitarse en todo aquello que él había leído que los caballeros andantes se ejercitaban.",
  "Deshaciendo todo género de agravio, y poniéndose en ocasiones y peligros donde, acabándolos, cobrase eterno nombre y fama.",
  "Imaginábase el pobre ya coronado por el valor de su brazo, al menos del imperio de Trapisonda.",
  "Y así, con estos tan agradables pensamientos, llevado del extraño gusto que en ellos sentía, se dio priesa a poner en efecto lo que deseaba.",
  "Y lo primero que hizo fue limpiar unas armas que habían sido de sus bisabuelos, que, tomadas de orín y llenas de moho, largo tiempo habían estado puestas y olvidadas en un rincón.",
  "Limpiólas y aderezólas lo mejor que pudo, pero vio que tenían una gran falta, y era que no tenían celada de encaje, sino morrión simple.",
  "Mas a esto suplió su industria, porque de cartones hizo un modo de media celada, que, encajada con el morrión, hacía una apariencia de celada entera.",
  "Es verdad que, para probar si era fuerte y podía estar al riesgo de una cuchillada, sacó su espada y le dio dos golpes, y con el primero y en un punto la deshizo.",
  "De lo cual le pareció no ser bien hacerse de nuevo, y, por repararla, hizo otros cartones, y, haciéndolos de nuevo, los afianzó con unas barras de hierro, de modo que quedó satisfecho de su fortaleza.",
  "Y sin querer hacer nueva experiencia dellos, los dio por celada finísima de encaje.",
  "Fue luego a ver su rocín, y aunque tenía más cuartos que un real y más tachas que el caballo de Gonela, que tantum pellis et ossa fuit, le pareció que ni el Bucéfalo de Alejandro ni Babieca el del Cid con él se igualaban.",
  "Cuatro días se le pasaron en imaginar qué nombre le pondría, porque, según se decía él a sí mesmo, no era razón que caballo de caballero tan famoso, y tan bueno él por sí, estuviese sin nombre conocido.",
  "Y así procuraba acomodársele de manera que declarase quién había sido antes que fuese de caballero andante, y lo que ahora era; que estaba muy puesto en razón que, mudando su señor estado, mudase él también el nombre, y le cobrase famoso y de gran sonoridad.",
  "Y así, después de muchos nombres que formó, borró y quitó, añadió, deshizo y tornó a hacer en su memoria e imaginación, al cabo le vino a llamar Rocinante, nombre a su parecer alto, sonoro y significativo de lo que había sido cuando fue rocín, antes de lo que ahora era.",
  "Puesto nombre, y tan a su gusto a su caballo, quiso ponérsele a sí mismo, y en este pensamiento duró otros ocho días.",
  "Y al cabo se vino a llamar don Quijote, de donde, como queda dicho, tomaron ocasión los autores desta tan verdadera historia que sin duda se debía de llamar Quijada, y no Quesada, como otros quisieron decir.",
  "Pero, acordándose que el valeroso Amadís no se había contentado con llamarse sin más Amadís, sino que añadió el nombre de su reino y patria, por hacerla famosa, y se llamó Amadís de Gaula, así quiso, como buen caballero, añadir al suyo el nombre de su patria y llamarse don Quijote de la Mancha.",
  "Con esto, como queda dicho, daba a entender muy al vivo su linaje y patria, y honrábala con tomar el sobrenombre della.",
  "Limpias, pues, sus armas, hecho del morrión celada, puesto nombre a su rocín y confirmándose a sí mismo, se dio a entender que no le faltaba otra cosa sino buscar una dama de quien enamorarse.",
  "Porque el caballero andante sin amores era árbol sin hojas y sin fruto, y cuerpo sin alma.",
  "Decíase él a sí: Si yo, por malos de mis pecados, o por mi buena suerte, me encuentro por ahí con algún gigante, como de ordinario les acontece a los caballeros andantes, y le derribo de un encuentro, o le parto por mitad del cuerpo, o, finalmente, le venzo y le rindo, ¿no será bien tener a quien enviarle presentado?",
  "Y que entre, y se hinque de rodillas ante mi dulce señora, y le diga con voz humilde y rendida: Yo, señora, soy el gigante Caraculiambro, señor de la ínsula Malindrania, a quien venció en singular batalla el jamás como se debe alabado caballero don Quijote de la Mancha.",
];

export { quijoteFrases };
